---

- name: "Install Preqrequisites"
  apt: name={{ item }} state=present update_cache=yes
  sudo: yes
  with_items:
      - git
      - maven
      - python-software-properties
      - software-properties-common
      - build-essential

- name: "Check thrift version"
  shell: "thrift --version"
  register: thrift_version
  failed_when: False
  changed_when: False

- name: "Install and update thrift"
  shell: "wget http://apache.mirrors.tds.net/thrift/0.9.2/thrift-0.9.2.tar.gz -O /tmp/thrift.tar.gz && cd /tmp && tar -xzf thrift.tar.gz && cd thrift-0.9.2 && ./configure --prefix=/usr --without-ruby --without-python --without-c
      --without-erlang --without-go --without-nodejs && make && make install"
  when: thrift_version.stdout != "Thrift version 0.9.2"
  sudo: yes

- name: "Install JAVA8 Repo"
  sudo: yes
  apt_repository: repo="ppa:webupd8team/java" update_cache=yes
  register: java8

- name: auto accept oracle jdk license
  when: java8.changed
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes

- name: install java8
  when: java8.changed
  apt: name=oracle-java8-installer force=yes update-cache=yes state=latest
  sudo: yes

- name: "Create CorfuDB git temporary repository directory"
  when: from_git is defined and from_git == true
  file: path=/tmp/CorfuDB state=directory

- name: "Install CorfuDB git sources"
  when: from_git is defined and from_git == true
  git: repo=https://github.com/CorfuDB/CorfuDB.git dest=/tmp/CorfuDB
  register: git_updated

- name: "Build CorfuDB from git sources"
  when: from_git is defined and from_git == true and git_updated.changed
  shell: mvn install chdir=/tmp/CorfuDB

- name: "Uninstall any old CorfuDB packages"
  when: from_git is defined and from_git == true and git_updated.changed
  apt: name={{ item }} state=absent
  sudo: yes
  with_items:
      - corfudb-logunit
      - corfudb-sequencer
      - corfudb-configmaster
      - corfudb-common

- name: "Install CorfuDB-common from git sources"
  when: from_git is defined and from_git == true
  sudo: yes
  apt: deb=/tmp/CorfuDB/target/corfudb_0.1~SNAPSHOT_all.deb

- name: "Set that CorfuDB is installed from git packaging"
  set_fact:
      corfudb_pkg_src: from_git
